# 00.PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have any questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
!nvidia-smi

Mon May 15 16:23:09 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.68                 Driver Version: 531.68       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060       WDDM | 00000000:01:00.0  On |                  N/A |
| 32%   36C    P5               26W / 184W|    887MiB / 12288MiB |     34%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## inIntroduction to Tensors
### Create tensors

PyTorch tensors are created using `torch.Tensor()` =  https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python integer

scalar.item()

7

In [6]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# get the dimensions of the vector
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# get the dimensions of the MATRIX
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim 

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [19]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3439, 0.4894, 0.8071, 0.1774],
        [0.0893, 0.2058, 0.4113, 0.2507],
        [0.8586, 0.5622, 0.8789, 0.8848]])

In [20]:
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3))  # hieght, width, colour channels(R,G,B)
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [22]:
random_image_size_tensor.ndim

3

### Zero and ones

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [27]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(0,11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Create tnesors like
# 利用另一個 TENSOR 的形狀來製作新的 TENSOR
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you wil run into with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [29]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               # https://pytorch.org/docs/stable/tensors.html
                               dtype=None,  # what datatype is the tensor (e.g. float32)
                               device = None,  # "cpu", "cude", what device is your tensor on
                               requires_grad = False) # whether or not to track gradients

float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [33]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [35]:
# create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5640, 0.9002, 0.9461, 0.6003],
        [0.4523, 0.6029, 0.2896, 0.8484],
        [0.4373, 0.2755, 0.8313, 0.2616]])

In [36]:
# find out details about some tensor

print(some_tensor)
print(f"DataType of tensor:{some_tensor.dtype}" ) 
print(f"DataType of tensor:{some_tensor.dtype}" )
print(f"Device tensor is on:{some_tensor.device}" )

tensor([[0.5640, 0.9002, 0.9461, 0.6003],
        [0.4523, 0.6029, 0.2896, 0.8484],
        [0.4373, 0.2755, 0.8313, 0.2616]])
DataType of tensor:torch.float32
DataType of tensor:torch.float32
Device tensor is on:cpu


### Manipulating Tensors (tensor operations)

Tensor opertions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [37]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

In [40]:
# try out PyTorch in-built functions
print(torch.mul(tensor,10))
print(torch.add(tensor,10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### **Matrix multiplication**

Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplication of matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimension** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`

Implemention on multiplication of matrices - http://matrixmultiplication.xyz/ - very useful to understand

In [41]:
# Element wise multiplication

print(tensor, "*" , tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [42]:
# Matrix multiplication (dot product)
torch.matmul(tensor,tensor)

tensor(14)

In [43]:
# Matric multiplication by hand
1*1 + 2*2 + 3*3

14

可以看使用 `torch.matmul(tensor,tensor)` 會比你直接用for迴圈做矩陣乘法快很多很多

In [44]:
%%time
value = 0 
for i in range (len(tensor)) :
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 998 µs


In [45]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [46]:
%%time
tensor @ tensor

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### **One of the most common errors in deep learning: shape errors**

Implemention on multiplication of matrices - http://matrixmultiplication.xyz/ - very useful to understand

In [47]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul(it is an alias for `tensor.matmul`)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [49]:
print(tensor_B, tensor_B.shape)
print(tensor_B.T, tensor_B.T.shape)

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]]) torch.Size([3, 2])
tensor([[ 7,  9, 11],
        [ 8, 10, 12]]) torch.Size([2, 3])


In [50]:
# The matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"new shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T{tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
new shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.Ttorch.Size([2, 3])
Multiplying:torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


## **Finding the min, max , mean, sum, etc (tensor aggregation)**

In [51]:
# create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [52]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [53]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [54]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
x = x.type(torch.float)
torch.mean(x), x.mean()

(tensor(45.), tensor(45.))

In [55]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

## **Finding the positional min and max**

In [56]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [57]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin() , x[0]

(tensor(0), tensor(0.))

In [58]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()  , x[9]

(tensor(9), tensor(90.))

## **Reshaping, stacking, squeezing and unsqueezing tensors**

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [59]:
# let's create a tensor

import torch

x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [60]:
# add an extra dimension
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [61]:
# Change the view

z = x.view(2,5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [62]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x


(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [63]:
# Stack tensors on top of each other
# reference: https://pytorch.org/docs/stable/generated/torch.stack.html

x_stacked = torch.stack([x,x,x],dim = 0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])

In [64]:
# reference: https://pytorch.org/docs/stable/generated/torch.hstack.html#torch-hstack

x_hstacked = torch.hstack([x,x,x])
x_hstacked

tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,
         5.,  5.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,
         9., 10.])

In [65]:
# reference: https://pytorch.org/docs/stable/generated/torch.vstack.html#torch-vstack

x_vstacked = torch.vstack([x,x,x])
x_vstacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])

In [66]:
# torch.squeeze() - remove all single dimensions from a target tensor
# https://pytorch.org/docs/stable/generated/torch.squeeze.html

print(f"previous tensor: {x_reshaped}")
print(f"previous tensor: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])
previous tensor: torch.Size([1, 10])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [67]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)

print(f"Previous target:{x_squeezed}")
print(f"Previous target:{x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"Previous target:{x_unsqueezed}")
print(f"Previous target:{x_unsqueezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"Previous target:{x_unsqueezed}")
print(f"Previous target:{x_unsqueezed.shape}")

Previous target:tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])
Previous target:torch.Size([10])
Previous target:tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])
Previous target:torch.Size([1, 10])
Previous target:tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 5.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
Previous target:torch.Size([10, 1])


In [68]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# reference: https://pytorch.org/docs/stable/generated/torch.permute.html

x_original = torch.rand(size = (224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [69]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## **Indexing (selecting data from tensors)**

Indexing with PyTorch is similar to indexing with NumPy.


In [70]:
# Create a tensor
import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [73]:
# Let's index on the most inner bracker (last dimension)
x[0][0][0]

tensor(1)

In [74]:
# You can alse use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [75]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [76]:
# Get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension

x[:,1,1]

tensor([5])

## **PyTorch tensors & NumPy**

NumPy is a popular scientific Python numerial computin livarary

and because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [77]:
# numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning : when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of flaot64 unless specified otherwise
# tensor = torch.from_numpy(array).type(torch.float32)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [78]:
array.dtype

dtype('float64')

In [79]:
torch.arange(1.0,8.0).dtype

torch.float32

In [80]:
# Change the value of array, what will this to do `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [81]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [82]:
# Change the tnesor, what happens to `numpy_tensor`?

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially waht the random seed does is "flavour" the randomness

In [83]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5398, 0.0256, 0.6560, 0.4769],
        [0.9090, 0.0787, 0.3949, 0.7602],
        [0.7530, 0.8498, 0.3206, 0.9588]])
tensor([[0.5279, 0.7459, 0.5880, 0.4929],
        [0.5186, 0.4586, 0.4742, 0.6681],
        [0.2334, 0.7340, 0.8314, 0.7809]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [84]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good)

### **1. Getting a GPU**

1. Eesiest - Use Google Colab for a free GPU (optios to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/category/deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [85]:
!nvidia-smi

Mon May 15 16:24:18 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.68                 Driver Version: 531.68       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060       WDDM | 00000000:01:00.0  On |                  N/A |
| 32%   36C    P8               22W / 184W|    873MiB / 12288MiB |     16%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### **2. Check for GPU access with PyTorch**

In [86]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it is capable of running compute on teh GPU or CPU, it is best prectice to setup device agnostic code:https://pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU

In [87]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [88]:
# Count number of device
torch.cuda.device_count()

1

### **3. Putting tensors (and models) on the GPU**

The reason we want our tensors/ models on the GPU is because using a GPU results in faster computations

In [89]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [90]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### **4. Moving tensors back to the CPU**

In [91]:
# If tensor is on GPU, can not transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [92]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [93]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## **Exercises & Extra-curriculum**

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises